Repository jenkins-infra/pipeline-library, pull requests merged in 2019-08, with the labels that each got.

#98 Enable Release Drafter for the repository
  .github/release-drafter.yml
Labels: chore

#93 Add Jenkins Pipeline Unit to the repository
  .gitignore
  Jenkinsfile
  pom.xml
  src/test/groovy/CustomWARPackagerStepTests.groovy
  src/test/groovy/EssentialsTestStepTests.groovy
  src/test/groovy/InfraStepTests.groovy
  src/test/groovy/PublishReportsStepTests.groovy
Labels: chore

#100 Jenkinsfile: remove the empty tools section from the Jenkinsfile
  Jenkinsfile
Labels: skip-changelog

#99 `buildPlugin()` - Cleanup plugin workspace and Docker images after build
  vars/buildPlugin.groovy
Labels: chore

#90 [INFRA-2028] `buildPlugin()` - Remove the timestamps step which is no longer necessary
  vars/buildPlugin.groovy
Labels: chore

#89 `buildPlugin()` - Archive Maven Failsafe Plugin reports
  .gitignore
  vars/buildPlugin.groovy
Labels: enhancement

#101 Remove static modifer
  vars/buildPlugin.groovy
Labels: skip-changelog

#103 Stop `buildPlugin` cleanup error log on ACI (regression in 1.1.0)
  vars/buildPlugin.groovy
Labels: bug

#106 `buildPlugin()` - Temporarily disable Windows builds and force ACI
  vars/buildPlugin.groovy
Labels: chore

#107 Switch `infra.maybePublishIncrementals()` to use an Azure Container Instance agent
  vars/infra.groovy
Labels: chore

#108 Revert "`buildPlugin()` - Temporarily disable Windows builds and force ACI"
  vars/buildPlugin.groovy
Labels: chore

#105 Add the VS Code project files to .gitignore
  .gitignore
Labels: chore

#110 Add forceAci parameter to `buildPlugin()`
  README.adoc
  vars/buildPlugin.groovy
Labels: enhancement

#109 Support Windows agents in the `buildPlugin()` Docker prune logic
  vars/buildPlugin.groovy
Labels: chore

#102 Add Unit Tests for `buildPlugin` and `runBenchmarks`
  src/test/groovy/BuildPluginStepTests.groovy
  src/test/groovy/CustomWARPackagerStepTests.groovy
  src/test/groovy/EssentialsTestStepTests.groovy
  src/test/groovy/PublishReportsStepTests.groovy
  src/test/groovy/RunBenchmarksStepTests.groovy
  src/test/groovy/mock/CurrentBuild.groovy
  src/test/groovy/mock/CustomWARPackager.groovy
  src/test/groovy/mock/Docker.groovy
  src/test/groovy/mock/Infra.groovy
  vars/buildPlugin.groovy
Labels: tests

#111 Add a new `infra.prepareToPublishIncrementals()` method to optimize the resource usage
  vars/infra.groovy
Labels: enhancement
