Repository jenkins-infra/pipeline-library, pull requests merged in 2019-12, with the labels that each got.

#123 maybePublishIncrementals could run on any Linux agent
  vars/infra.groovy
Labels: chore

#124 Activate the benchmark profile directly rather than indirectly via a property
  vars/runBenchmarks.groovy
Labels: chore

#125 Add tests.skip option for Gradle based plugins + Documentation formatting fixes
  README.adoc
  vars/buildPlugin.groovy
  vars/buildPluginWithGradle.groovy
Labels: documentation, enhancement

#126 Skip test result collection if tests are skipped
  vars/buildPluginWithGradle.groovy
Labels: enhancement

#127 Add tests for buildPluginWithGradle
  src/test/groovy/BuildPluginWithGradleStepTests.groovy
  src/test/groovy/mock/Infra.groovy
Labels: chore

#128 Fix default value handling for `archiveArtifacts` and `installArtifacts` Boolean properties
  vars/customWARPackager.groovy
Labels: bug

#88 Always collect test results after running the build
  vars/buildPlugin.groovy
  vars/buildPluginWithGradle.groovy
Labels: enhancement

#129 Use explicit types for Custom WAR Packager settings
  vars/customWARPackager.groovy
Labels: chore
