Repository jenkins-infra/pipeline-library, pull requests merged in 2025-03, with the labels that each got.

#914 fix(infra/Windows/checkoutSCM) Ensure Git LongPath is set at system level
  vars/infra.groovy
Labels: cleanup

#913 feat(updatecli): Add custom version execution of updatecli
  test/groovy/UpdatecliStepTests.groovy
  vars/updatecli.groovy
Labels: enhancement

#919 fix(infra) fix a potential memory leak related to missing type for `orgAndCredentialsId`
  vars/infra.groovy
Labels: bug
